### ISSUE TITLE
Instruction Embedding

### ISSUE THREAD

**Issue by peicwang** [DeepBitsTechnology/DeepDi#2]
Hi, I am very interested in the instruction embedding method used in your paper. In the paper, as you mentioned, there are a total of 1025 unique opcodes. Would you mind providing a dictionary of opcodes? For me, this instruction representation is quite interesting, so I wonder how it works.

**Comment by Nifury** [comment]
There are 1-, 2- (`0F XX`), and 3-byte (`0F 38 XX` or `0F 3A XX`) opcodes, so roughly about 1024 combinations in total. We also added a new opcode representing "invalid opcode", and that's why we have 1025 unique opcodes. 

Opcode itself doesn't uniquely represent an instruction. Sometimes we need prefix, opcode, and modrm to determine the mnemonics of an instruction. That's why there are thousands of mnemonics but only about 1024 opcodes. 

Here are some useful links for [x86 opcodes](http://ref.x86asm.net/coder.html) and [instruction encoding](http://www.c-jump.com/CIS77/CPU/x86/lecture.html).

**Comment by peicwang** [comment]
Except for ”invalid opcode“, in the remaining 1024 cases, one-byte opcodes (00-FF), two-byte opcode (0F 00 - 0F FF ), three-byte opcode (0F 38 00 - 0F 38 FF or 0F 3A 00 - 0F 3A FF), so there are 1024 cases in total, but in these cases, there are a lot of redundant opcodes, such as the one-byte opcode 0F, which itself cannot be parsed as a mnemonic, but represents two-Byte escape, and in three-byte opcode, there are a large number of opcode combinations that are reserved and have no specific meaning, so is it reasonable to build such a redundant dictionary? Or would it be better to reduce redundant cases?

**Comment by Nifury** [comment]
Sure it's better to reduce the redundant cases, but there are also cases where certain combinations of opcode/modrm/sib are invalid. Some simple cases such as invalid/reserved opcodes can be easily detected during instruction decoding, and they are marked using the special "invalid opcode" token. We leave the rest, more complicated cases to the neural network. 

In other words, there are some entries in the dictionary that are never used, but I don't think it will cause any issue.

**Comment by peicwang** [comment]
I see, thanks for your reply！
